//Define the Actions
export const GET_CATEGORY_LOADING = 'GET_CATEGORY_LOADING';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';

export const GET_SUBCATEGORY_LOADING = 'GET_SUBCATEGORY_LOADING';
export const GET_SUBCATEGORY_FAIL = 'GET_SUBCATEGORY_FAIL';
export const GET_SUBCATEGORY_SUCCESS = 'GET_SUBCATEGORY_SUCCESS';

export const GET_CATEGORY_ID_LOADING = 'GET_CATEGORY_ID_LOADING';
export const GET_CATEGORY_ID_FAIL = 'GET_CATEGORY_ID_FAIL';
export const GET_CATEGORY_ID_SUCCESS = 'GET_CATEGORY_ID_SUCCESS';

export const GET_SUBCAT_FOR_CAT_LOADING = 'GET_SUBCAT_FOR_CAT_LOADING';
export const GET_SUBCAT_FOR_CAT_FAIL = 'GET_SUBCAT_FOR_CAT_FAIL';
export const GET_SUBCAT_FOR_CAT_SUCCESS = 'GET_SUBCAT_FOR_CAT_SUCCESS';

export const GET_SUBCATEGORY_ID_LOADING = 'GET_SUBCATEGORY_ID_LOADING';
export const GET_SUBCATEGORY_ID_FAIL = 'GET_SUBCATEGORY_ID_FAIL';
export const GET_SUBCATEGORY_ID_SUCCESS = 'GET_SUBCATEGORY_ID_SUCCESS';
