//Define the Actions
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_FOR_SUBCAT_LOADING = 'GET_PRODUCTS_FOR_SUBCAT_LOADING';
export const GET_PRODUCTS_FOR_SUBCAT_FAIL = 'GET_PRODUCTS_FOR_SUBCAT_FAIL';
export const GET_PRODUCTS_FOR_SUBCAT_SUCCESS = 'GET_PRODUCTS_FOR_SUBCAT_SUCCESS';

export const GET_PRODUCT_ID_LOADING = 'GET_PRODUCT_ID_LOADING';
export const GET_PRODUCT_ID_FAIL = 'GET_PRODUCT_ID_FAIL';
export const GET_PRODUCT_ID_SUCCESS = 'GET_PRODUCT_ID_SUCCESS';